#!/bin/bash

#Checking for installation of xautomation
if ! [ -x "$(command -v xte)" ]; then
  echo 'Xautomation is not installed and is required, installing xautomation.'
  apt-get install xautomation
  exit 1
fi

if ! [ -x "$(command -v xclip)" ]; then
  echo 'Xautomation is not installed and is required, installing xautomation.'
  apt-get install xclip
  exit 1
fi

#Local File Assumption
file_local=0
file="rst"

#If local file then moving to /usr/bin
if [ -f "$file" ]; then
	chmod +x rst
	echo "RST file found locally moving to /usr/bin"
  	file_local=1
  	rm /usr/bin/rst
  	cp rst /usr/bin/rst
  	chmod +x /usr/bin/rst

#No local file, wgetting for repo and putting in /usr/bin
else
	if [ -f "/usr/bin/rst" ]; then
		rm /usr/bin/rst
	fi
	wget https://raw.githubusercontent.com/mustansirgodhrawala/rst/master/setup
	mv rst /usr/bin/rst
	chmod +x /usr/bin/rst
	echo "Downloaded file... now moving to /usr/bin"
fi

